stages:
  - test
  - build
  - deploy

test:
  image: node:18
  stage: test
  script:
    - cd backend
    - npm install
    - npm test

build:
  image: docker:latest
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest ./backend
  only:
    - main

deploy:
  image: docker:latest
  stage: deploy
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main
