version: "3.8"

services:
  backend:
    build: ./backend
    container_name: express-api
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
    env_file:
      - ./backend/.env