name: CI/CD Express Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer les dépendances
        run: |
          cd backend
          npm install

      - name: Exécuter les tests Jest
        run: |
          cd backend
          npm test

  build-and-push:
    needs: test  # ✅ Ce job s'exécute SEULEMENT si les tests réussissent
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Se connecter à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construire l’image Docker avec le bon tag
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/express-api:latest ./backend

      - name: Vérifier les images disponibles
        run: docker images

      - name: Pousser l’image sur Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/express-api:latest